language: c

compiler:
  - clang
  - gcc

dist: xenial

addons:
  apt:
    packages:
      - libnl-genl-3-dev
      - libssl-dev

script:
  - make -C wpa_supplicant

before_deploy:
  - "mkdir -p wpa_sycophant/wpa_supplicant"
  - "cp wpa_sycophant.sh wpa_sycophant_example.conf wpa_sycophant"
  - "cp wpa_supplicant/wpa_supplicant wpa_sycophant/wpa_supplicant/wpa_supplicant"
  - "tar -zcf wpa_sycophant.tar.gz wpa_sycophant"

deploy:
  provider: releases
  api_key: $GIT_TOKEN
  file: wpa_sycophant.tar.gz
  on:
    repo: Cablethief/wpa_sycophant
    tags: true
    condition: "$CC = gcc"
    branch: master
  overwrite: true
  prerelease: true
  skip_cleanup: true
